apiVersion: v1
kind: Pod
metadata:
  name: label-defination-1
  labels:
    app: app-1
spec:
  containers:
    - name: label-defination-cn
      image: node
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 5000

# apiVersion: v1
# kind: Pod
# metadata:
#   name: label-defination-2
#   labels:
#     app: app-2
# spec:
#   containers:
#     - name: label-defination-cn
#       image: nginx
#       resources:
#         limits:
#           memory: "128Mi"
#           cpu: "500m"
#       ports:
#         - containerPort: 5000